version: 2.1
jobs:
  build-and-test:
    working_directory: ~/project
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --legacy-peer-deps
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test for the application
          command: yarn run test:unit
workflows:
  build-and-test:
    jobs:
      - build-and-test